### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by alexislefebvre** [ro0NL/composer-link#3]
I'm trying to work on a project `B` that is a dependency of the project `A`. I created a branch in the project `B`.

I installed this package globally and I ran `composer link /path/to/B` in the project `A`.

It looks like nothing happened.

If I run a `composer install` it shows that dependencies are broken.

Am I missing something?

**Comment by ro0NL** [comment]
Hi @alexislefebvre, `link` will find all packages in the current working directory (recursively), then it looks for those packages installed in a project (the path you specify). If found it's `vendor/some/package` is removed (!) and symlinked to the package found in the current working directory.

**Comment by alexislefebvre** [comment]
Thanks, so there's no need to launch `composer update` or something link that.

**Comment by ro0NL** [comment]
Nope, it's a straightforward symlink on the filesystem. Given the Symfony example in the README that would be e.g.:

```
./project/vendor/symfony/config -> ./symfony/src/Symfony/Component/Config/
```
